server:
  port: 8095
spring:
  datasource:
    url: jdbc:mysql://120.77.221.159/enquipment
    username: root
    password: Tan@8888
    validationQuery: SELECT 1
    testWhileIdle: true
    timeBetweenEvictionRunsMillis: 50000
  redis:
    host: 120.77.221.159
    password: Lan8568@123
